name: App Distribution

on:
  push:
    branches:
      - main

jobs:
  firebase_app:
    name: Distributing App
    runs-on: ubuntu-latest ## virtual machine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Build Release App
        run: flutter pub get && flutter build apk --dart-define=API_URL=${{ secrets.API_URL }} 

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: ./build/app/outputs/apk/release/app-release.apk

      - name: Distribute App
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: main-users
          file: ./build/app/outputs/flutter-apk/app-release.apk
      
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: v1.0.2
          release_name: Release v1.0.2
          draft: false
          prerelease: false

      - name: Upload Release APK to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive