name: App Distribution

on:
  push:
    branches:
      - main

jobs:
  firebase_app:
    name: Distributing App
    runs-on: ubuntu-latest ## virtual machine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Build Release App
        run: flutter pub get && flutter build apk --dart-define=API_URL=${{ secrets.API_URL }} --dart-define=FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} --dart-define=FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }} --dart-define=FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} 

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: ./build/app/outputs/apk/release/app-release.apk

      - name: Distribute App
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: main-users
          file: ./build/app/outputs/flutter-apk/app-release.apk